const data = [
  {
    id:1,
    img:"/images/interior1.jpg",
    category:"for rent",
    name:"6335 N Magnolia Ave Apt 1S",
    location:"Chicago, IL 60660",
    foot:"2200 square foot",
    bedroom:"4 Bedrooms",
    garage:"1 Garage",
    bathroom:"5 Bathrooms",
    time:"3 days ago",
    user:"john kenedy",
    prize:"1,800/month",
    background:true
  },
    {
    id:2,
    img:"/images/sale.jpg",
    category:"for sale",
    name:"441 E Maywood Ct",
    location:"Decatur, IL 62526",
    foot:"750",
    bedroom:"16 Bedrooms",
    garage:"4 Garage",
    bathroom:"10 Bathrooms",
    time:"8 days ago",
    user:"sam dede",
    prize:"1,600,000",
    background:false
  },
    {
    id:3,
    img:"/images/sale1.jpg",
    category:"for sale",
    name:"712 Southland Circle Dr",
    location:"Tuscola, IL 61953",
    foot:"1200 square foot",
    bedroom:"6 Bedrooms",
    garage:"2 Garage",
    bathroom:"12 Bathrooms",
    time:"3 days ago",
    user:"Gina Wasley",
    prize:"105,000",
    background:false

  },  {
    id:4,
    img:"/images/sale2.jpg",
    category:"for sale",
    name:"1476 Havard St NW Unti Ph",
    location:"Washington DC 50021",
    foot:"2500 square foot",
    bedroom:"8 Bedrooms",
    garage:"3 Garage",
    bathroom:"10 Bathrooms",
    time:"1 days ago",
    user:"kingley ruth",
    prize:"1,250,000",
    background:false
  },  {
    id:5,
    img:"/images/rent5.jpg",
    category:"for rent",
    name:"9633 Weathered Oak Ct",
    location:"Bethesda,MD 208179",
    foot:"2200 square foot",
    bedroom:"3 Bedrooms",
    garage:"1 Garage",
    bathroom:"4 Bathrooms",
    time:"9 days ago",
    user:"james annah",
    prize:"2500/month",
    background:true
  },  {
    id:6,
    img:"/images/rent4.jpg",
    category:"for rent",
    name:"2529 Marsh Hill Henry Rd Unit Mc",
    location:"McHenry, NA 10072",
    foot:"450 square foot",
    bedroom:"2 Bedrooms",
    garage:"1 Garage",
    bathroom:"2 Bathrooms",
    time:"3 days ago",
    user:"araphat joy",
    prize:"1,000/month",
    background:true
  },  {
    id:7,
    img:"/images/interior5.jpg",
    category:"for rent",
    name:"6335 N Magnolia Ave Apt 1S",
    location:"Chicago, IL 60660",
    foot:"2200 square foot",
    bedroom:"2 Bedrooms",
    garage:"1 Garage",
    bathroom:"2 Bathrooms",
    time:"3 days ago",
    user:"dele mr.brown",
    prize:"650/month",
    background:true
  },  {
    id:8,
    img:"/images/sale5.jpg",
    category:"for sale",
    name:"6335 N Magnolia Ave Apt 1S",
    location:"Chicago, IL 60660",
    foot:"1500 square foot",
    bedroom:"4 Bedrooms",
    garage:"1 Garage",
    bathroom:"5 Bathrooms",
    time:"6 days ago",
    user:"ramson doe",
    prize:"2,600,000",
    background:false
  },  {
    id:9,
    img:"/images/interior6.jpg",
    category:"for rent",
    name:"Sofi Berrysea 750 N king road",
    location:"San jose, CA 32564",
    foot:"900 square foot",
    bedroom:"4 Bedrooms",
    garage:"1 Garage",
    bathroom:"5 Bathrooms",
    time:"2 days ago",
    user:"mauren gina",
    prize:"2,110/month",
    background:true
  },  {
    id:10,
    img:"/images/sale4.jpg",
    category:"for sale",
    name:"1203 Orren Street, Northeast",
    location:"Washington, DC 20002",
    foot:"200 square foot",
    bedroom:"3 Bedrooms",
    garage:"1 Garage",
    bathroom:"4 Bathrooms",
    time:"4 days ago",
    user:"terry mia",
    prize:"1,100,000",
    background:false
  },  {
    id:11,
    img:"/images/interior3.jpg",
    category:"for rent",
    name:"301 North Palm Drive",
    location:"Beverly Hills, CA 9012",
    foot:"2200 square foot",
    bedroom:"1 Bedrooms",
    garage:"1 Garage",
    bathroom:"2 Bathrooms",
    time:"3 days ago",
    user:"Fofana Benaldo",
    prize:"550/month",
    background:true
  },  {
    id:12,
    img:"/images/sale3.jpg",
    category:"for sale",
    name:"1963 S Crescent Heights Blvd",
    location:"Los Angeles, CA 30021",
    foot:"2200 square foot",
    bedroom:"4 Bedrooms",
    garage:"2 Garage",
    bathroom:"5 Bathrooms",
    time:"11 days ago",
    user:"mike jowel",
    prize:"3,110,000",
    background:false
  }
]
export default data